version: '3.9'
services:
  app:
    container_name: nodejs
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    volumes:
      - ./:/app
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
    networks:
      - postgres

  postgres:
    container_name: postgres-db
    build: ./src/database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  app:
  ignore:
  postgres:
