version: '3.9'
services:
  app:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest